import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { Provider } from '@fullstack-trello-clone/trpc-client/src/Provider'
import { SessionProvider } from '@/components/SessionProvider'
// import { SessionProvider } from '@fullstack-trello-clone/ui/src/components/molecules/SessionProvider'
import { Container } from '@fullstack-trello-clone/ui/src/components/atoms/Container'
import { Navbar } from '@fullstack-trello-clone/ui/src/components/organisms/Navbar'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
          <Provider>
            <header className="bg-gray-200 p-4">
              <a href="/" className="logo">
                Trello
              </a>
            </header>
            <Container>{children}</Container>
          </Provider>
        </SessionProvider>
      </body>
    </html>
  )
}
